# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c31261282e2301c5eed3e6313917be762abee0cbd87a13849f11309adff87bc7d9be385634385c65ddf0b73008ebe2043ff535f603d364b9d06318016291da6a

test:
  secret_key_base: c884cf95f438c2f747c8821c52ad52907b9d87a336ac599aeb12b72a86948c65ffa8d7ff63ccb61801b010061d2f66a853db1d55c0ce82d7742484dc9088a623

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
